theme: jekyll-theme-dinky
github:
  owner_url: https://zrouter.org
  repository_url: https://github.com/ZRouter/ZRouter
webrick:
  headers:
    My-Header: My-Value
    My-Other-Header: My-Other-Value
